# Generated by Django 3.2 on 2021-10-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0421_alter_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
