# Generated by Django 3.0.4 on 2021-10-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0422_customer_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_bankwise',
            name='centre_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
