# Generated by Django 3.0.4 on 2021-10-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0423_auto_20211018_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='centercode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cloan',
            name='center',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='centercode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanbillsdata',
            name='centercode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_dailydata',
            name='centercode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_loan',
            name='center',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='centre_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
