# Generated by Django 3.0.4 on 2021-10-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0426_auto_20211020_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpt_daily_sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('custcode', models.CharField(blank=True, max_length=255, null=True)),
                ('custName', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('orderNo', models.IntegerField(default=0)),
                ('custType', models.CharField(blank=True, max_length=15, null=True)),
                ('prodCode', models.CharField(blank=True, max_length=25, null=True)),
                ('prodName', models.CharField(blank=True, max_length=25, null=True)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('couponCode', models.CharField(blank=True, max_length=25, null=True)),
                ('disc', models.FloatField(blank=True, default=0.0, null=True)),
                ('comm', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('unitRate', models.FloatField(blank=True, default=0.0, null=True)),
                ('netAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('ZoneCode', models.CharField(blank=True, max_length=255, null=True)),
                ('ZoneName', models.CharField(blank=True, max_length=255, null=True)),
                ('SaleExecCode', models.CharField(blank=True, max_length=255, null=True)),
                ('SaleExecName', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
                ('did1', models.IntegerField(default=0)),
                ('oid1', models.IntegerField(default=0)),
                ('cid1', models.IntegerField(default=0)),
                ('pid1', models.IntegerField(default=0)),
                ('zid1', models.IntegerField(default=0)),
                ('sid1', models.IntegerField(default=0)),
            ],
        ),
    ]
