# Generated by Django 3.0.4 on 2021-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0428_rpt_daily_sales_subtot'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='RecAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='recDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='recNo',
            field=models.IntegerField(default=0),
        ),
    ]
