# Generated by Django 3.0.4 on 2021-10-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0430_daily_receipts_recno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_sales',
            old_name='recNo',
            new_name='recptNo',
        ),
    ]
