# Generated by Django 3.0.4 on 2021-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0431_auto_20211028_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_daily_sales',
            name='osAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_daily_sales',
            name='recAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_daily_sales',
            name='recDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
