# Generated by Django 3.0.4 on 2021-10-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0432_auto_20211029_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='recRefNo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rpt_daily_sales',
            name='recRefNo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
