# Generated by Django 3.0.4 on 2021-11-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0433_auto_20211029_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='indentdataexcelextract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('Saledate', models.DateField(blank=True, null=True)),
                ('custcode', models.CharField(blank=True, max_length=255, null=True)),
                ('custName', models.CharField(blank=True, max_length=255, null=True)),
                ('WM10L', models.FloatField(blank=True, default=0.0, null=True)),
                ('WM20L', models.FloatField(blank=True, default=0.0, null=True)),
                ('WM40L', models.FloatField(blank=True, default=0.0, null=True)),
                ('WMSPL', models.FloatField(blank=True, default=0.0, null=True)),
                ('SKM', models.FloatField(blank=True, default=0.0, null=True)),
                ('TM', models.FloatField(blank=True, default=0.0, null=True)),
                ('RCM', models.FloatField(blank=True, default=0.0, null=True)),
                ('CURD10KB', models.FloatField(blank=True, default=0.0, null=True)),
                ('CURD20KB', models.FloatField(blank=True, default=0.0, null=True)),
                ('CURD40KB', models.FloatField(blank=True, default=0.0, null=True)),
                ('CURD5KB', models.FloatField(blank=True, default=0.0, null=True)),
                ('CURD1KB', models.FloatField(blank=True, default=0.0, null=True)),
                ('TOTINDENT', models.FloatField(blank=True, default=0.0, null=True)),
                ('INDENTAMT', models.FloatField(blank=True, default=0.0, null=True)),
                ('RECAMT', models.FloatField(blank=True, default=0.0, null=True)),
                ('BALAMT', models.FloatField(blank=True, default=0.0, null=True)),
                ('RECDATE', models.DateField(blank=True, null=True)),
                ('recType', models.CharField(blank=True, max_length=25, null=True)),
                ('RecRemarks', models.CharField(blank=True, max_length=50, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('sourcedata', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
