# Generated by Django 3.0.4 on 2021-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0434_indentdataexcelextract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_sales',
            name='remove',
            field=models.CharField(blank=True, default='FI', max_length=3, null=True),
        ),
    ]
