# Generated by Django 3.0.4 on 2021-11-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0436_saleorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='recptNo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
