# Generated by Django 3.0.4 on 2021-11-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0437_auto_20211108_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_daily_sales',
            name='recAmount',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='OSAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
