# Generated by Django 3.0.4 on 2021-11-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0438_auto_20211111_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_sales',
            name='RecAmount',
        ),
    ]
