# Generated by Django 3.0.4 on 2021-11-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0439_remove_daily_sales_recamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_receipts',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='daily_receipts',
            name='updated_by',
        ),
    ]
