# Generated by Django 3.0.4 on 2021-11-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0441_customer_custserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='prodLabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prodtype',
            name='pTypeLabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
