# Generated by Django 3.0.4 on 2021-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0443_auto_20211115_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='milkUnits',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
