# Generated by Django 3.0.4 on 2021-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0447_prodmaster_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='UOM',
            field=models.CharField(blank=True, default='KG', max_length=5, null=True),
        ),
    ]
