# Generated by Django 3.0.4 on 2021-11-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0448_prodmaster_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='HSN',
            field=models.CharField(blank=True, default='-', max_length=5, null=True),
        ),
    ]
