# Generated by Django 3.0.4 on 2021-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0449_prodmaster_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodmaster',
            name='HSN',
            field=models.CharField(blank=True, default='-', max_length=15, null=True),
        ),
    ]
