# Generated by Django 3.0.4 on 2021-11-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0450_auto_20211121_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='customerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='qtyinUnits',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
