# Generated by Django 3.0.4 on 2021-11-27 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0451_auto_20211123_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('custcode', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('orderNo', models.IntegerField(default=0)),
                ('comm', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('netAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('remove', models.CharField(blank=True, default='FI', max_length=3, null=True)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
                ('updatedd', models.DateTimeField(default=django.utils.timezone.now)),
                ('crreatedd', models.DateTimeField(default=django.utils.timezone.now)),
                ('recptNo', models.IntegerField(blank=True, default=0, null=True)),
                ('recDate', models.DateField(blank=True, null=True)),
                ('RecAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('recRefNo', models.CharField(blank=True, max_length=25, null=True)),
                ('OSAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('WAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('curdqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('milkqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('gheeqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('paneerqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('kovaqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('hfmqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('fsmqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('othqty', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createIndent', to=settings.AUTH_USER_MODEL)),
                ('upt_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updIndent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
