# Generated by Django 3.0.4 on 2021-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0452_indent'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='CURD10KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD10KGCANQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD1KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD20KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD20KGCANQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD40KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD5KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURD5KGPOTQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURDDTM10KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURDDTM10KGCANQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='CURDTM10KGBQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='GHEE1KGQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='GHEE250GMSQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='GHEE500GMSQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='HIGHFATMILKQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='KOVA1KGQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='KOVA5KGQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='MILK10LQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='MILK1LQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='MILK20LQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='MILK40LQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='PANEER1KGQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='PANEER500GMSQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
