# Generated by Django 3.0.4 on 2021-12-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0454_auto_20211128_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_receipts',
            name='entryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_receipts',
            name='entryUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
