# Generated by Django 3.0.4 on 2021-12-02 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0455_auto_20211201_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='equip_receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('custcode', models.CharField(blank=True, max_length=255, null=True)),
                ('eqRecNo', models.IntegerField(default=0)),
                ('eqRecdate', models.DateField(blank=True, null=True)),
                ('eqType', models.CharField(blank=True, max_length=15, null=True)),
                ('eqRefNo', models.CharField(blank=True, max_length=25, null=True)),
                ('eqUnits', models.FloatField(blank=True, default=0.0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('entryDate', models.DateField(blank=True, null=True)),
                ('entryUser', models.CharField(blank=True, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, null=True)),
                ('updateUser', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
