# Generated by Django 3.0.4 on 2021-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0456_equip_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_receipts',
            name='custcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
