# Generated by Django 3.0.4 on 2021-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0457_daily_receipts_custcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='OSAMT',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='RAmt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='WAmt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
