# Generated by Django 3.0.4 on 2021-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0459_daily_sales_pamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='prodQ',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='prodmaster',
            name='qtyL',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
