# Generated by Django 3.0.4 on 2022-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0460_auto_20211219_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_receipts',
            name='updateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_receipts',
            name='updateUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_receipts',
            name='payRefNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_receipts',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_receipts',
            name='remove',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
