# Generated by Django 3.0.4 on 2022-01-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0461_auto_20220105_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_receipts',
            name='updRemarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
