# Generated by Django 3.2.8 on 2022-01-08 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0462_daily_receipts_updremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_pic_receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('orderNo', models.IntegerField(default=0)),
                ('custcode', models.CharField(blank=True, max_length=255, null=True)),
                ('recNo', models.IntegerField(default=0)),
                ('recdate', models.DateField(blank=True, null=True)),
                ('recType', models.CharField(blank=True, max_length=15, null=True)),
                ('payRefNo', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('remove', models.CharField(blank=True, max_length=25, null=True)),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('wamount', models.FloatField(blank=True, default=0.0, null=True)),
                ('entryDate', models.DateField(blank=True, null=True)),
                ('entryUser', models.CharField(blank=True, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, null=True)),
                ('updateUser', models.CharField(blank=True, max_length=50, null=True)),
                ('updRemarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
