# Generated by Django 3.2.8 on 2022-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0463_daily_pic_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_pic_receipts',
            name='billAmt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='daily_pic_receipts',
            name='pendAmt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
