# Generated by Django 3.2.8 on 2022-01-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0464_auto_20220110_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_pic_receipts',
            name='billAmt',
        ),
        migrations.RemoveField(
            model_name='daily_pic_receipts',
            name='pendAmt',
        ),
    ]
